# Get all books
GET http://localhost:3002/books HTTP/1.1
Content-Type: application/json

###
# Create a new book
POST http://localhost:3002/books HTTP/1.1
Content-Type: application/json

{
  "title": "The Lord of the Rings",
  "id": 1
}

###
# Update a book
PUT http://localhost:3002/books/1 HTTP/1.1
Content-Type: application/json

{
  "title": "The Lord of the Flowers",
}

###
# Delete a book
DELETE http://localhost:3002/books/1 HTTP/1.1
Content-Type: application/json
```